#!/bin/bash
echo
echo Delete all files not needed in the git push
echo -------------------------------------------
rm config.h             2>/dev/null
rm config.h.in~         2>/dev/null
rm config.log           2>/dev/null
rm config.status        2>/dev/null
rm stamp-h1             2>/dev/null
rm autom4te.cache/*     2>/dev/null
rmdir autom4te.cache    2>/dev/null
rm src/*.o              2>/dev/null
rm src/evenja           2>/dev/null
rm -rf deploy/          2>/dev/null
rm -rf src/deploy/      2>/dev/null
rm Makefile             2>/dev/null
rm src/Makefile         2>/dev/null
exit 0
